### ISSUE TITLE
Create a Filter for Embedded Video

### ISSUE THREAD

**Issue by chrisdaaz** [nulib-oer/lantern#33]
We need a Lua filter that can identify specific strings of text within a Markdown image element in order to generate an `<iframe>` HTML element. This will simplify the process of embedding videos from YouTube or Vimeo using Markdown syntax for the output formats that Lantern supports. 

For example, the filter will be able to identify this syntax: 

```
![](youtube:FEFETKhhq8w)
```

and generate this HTML:

```
<iframe allowfullscreen mozallowfullscreen frameborder="0" src="//www.youtube.com/embed/FEFETKhhq8w" webkitallowfullscreen></iframe>
```

The idea is for the filter to look for Markdown images that include "youtube:" in the source, copy the video id, then place it within some boilerplate HTML:

```
<iframe allowfullscreen mozallowfullscreen frameborder="0" src="//www.youtube.com/embed/{{ VIDEO_ID }}" webkitallowfullscreen></iframe>
```

Based on https://github.com/unmanbearpig/pandoc-videofilter

**Comment by AngelinaJaglinski** [comment]
The embed-video.lua filter is the final version of the filter.  This should work as expected.  The embed-specific-video.lua filter was one of my earlier steps, where you have to manually type out the string for each video you want to include in the HTML output.  It's far from comprehensive, but I thought it might be helpful to include as a reference.  (Both lua filters are  attached here as txt files since GitHub won't let me attach lua files.)

I have also attached the markdown file I was testing on.  The embed-video filter should work on any markdown file, but again, I thought I'd include my test file in case something came up.

[embed-specific-video.txt](https://github.com/nulib-oer/lantern/files/6859300/embed-specific-video.txt)
[embed-video.txt](https://github.com/nulib-oer/lantern/files/6859301/embed-video.txt)
[01-introduction.md](https://github.com/nulib-oer/lantern/files/6859302/01-introduction.md)

**Note**: Since the ![ ] syntax embeds images, I used the curly brace syntax:
{}(youtube:FEFETKhhq8w)
as a placeholder instead.

**Comment by chrisdaaz** [comment]
Thanks, @AngelinaJaglinski

What if we wanted to change the markdown syntax to this?

```
{{ youtube:FEFETKhhq8w }}
```

How would this line (or the rest of the filter) change?

```
md_string = string.match(inputstr, "{}"..".".."youtube:".."............")
```

**Comment by AngelinaJaglinski** [comment]
@chrisdaaz It seems that blocks in Pandoc are (in part) separated by space characters, causing some issues with this syntax: `{{ youtube:FEFETKhhq8w }}`.

However, this syntax: `{{youtube:FEFETKhhq8w}}` does work since there are no space charcters to seperate the block of text.   If this syntax is ok with you, the two changes to the filter would be:

1. `md_string = string.match(inputstr, "{{".."youtube:".."...........".."}}")`
2. `key = string.sub(inputstr, 11, len-2)` in the get_key function 
(`string.sub` basically splices the key from the markdown text, which will change depending on the syntax we choose)

I'll attach the new filter here as well.  If you do prefer the syntax with spaces, I can look into how Pandoc iterates through elements more in-depth.  Otherwise, I think these changes should work!

[embed-video.txt](https://github.com/nulib-oer/lantern/files/6864848/embed-video.txt)
